# -*- coding: utf-8 -*-
"""Introdução a machine learning projeto 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oRvtnLSAMkNxkEW5DYgCk-fV1J5d5x-l
"""

import pandas as pd

uri = 'https://gist.githubusercontent.com/guilhermesilveira/4d1d4a16ccbf6ea4e0a64a38a24ec884/raw/afd05cb0c796d18f3f5a6537053ded308ba94bf7/car-prices.csv'
dados = pd.read_csv(uri)
dados.head()

a_renomear = { 'mileage_per_year':'milhas_por_ano',
              'model_year':'modelo_ano',
              'price':'preço',
              'sold':'vendido'
    }

dados = dados.rename(columns = a_renomear)
dados.head()

a_trocar = { 'yes':1,
            'no':0}

dados.vendido.map(a_trocar) 
dados.vendido = dados.vendido.map(a_trocar)#sobrescrevendo a coluna de "vendidos"
dados.head()

